export const DARK_THEME = "DARK_THEME";
export const LIGHT_THEME = "LIGHT_THEME";

export const CATCH_POKEMON = "CATCH_POKEMON";
export const RELEASE_POKEMON = "RELEASE_POKEMON";

export const FAVORITE_POKEMON = "FAVORITE_POKEMON";
export const UNFAVORITE_POKEMON = "UNFAVORITE_POKEMON";